int x, y;
// x = 2;
// y = 3;
x = Convert.ToInt32(Console.ReadLine());
y = Convert.ToInt32(Console.ReadLine());
// Convert.ToInt32(x);
// Convert.ToInt32(y);
Console.WriteLine(x + y);
Console.WriteLine(x - y);
Console.WriteLine(x * y);
Console.WriteLine(x / y);       
